<%@ Page Title="" Language="C#" MasterPageFile="~/index.Master" AutoEventWireup="true" CodeBehind="ChinhSachDoiTra.aspx.cs" Inherits="WebSiteBanHang.TinTuc" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml">
        <head>
             <meta charset="utf-8"/>
            <title></title>
        </head>

        <body>
       <div style="padding:10px 200px 0 200px">
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
           <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
           <asp:Label ID="Label2" runat="server" Font-Bold="False" Font-Italic="False" Font-Overline="False" Font-Size="XX-Large" Font-Strikeout="False" Font-Underline="False" ForeColor="#009999" Text="Chính sách đổi trả với hàng từ nước ngoài"></asp:Label>
           <br />
           <p style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
               <strong style="box-sizing: border-box; font-weight: bold;">1. Định nghĩa:</strong></p>
           <p style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
               <strong style="box-sizing: border-box; font-weight: bold;">Hàng quốc tế</strong><span>&nbsp;</span>là những sản phẩm được cung cấp qua biên giới bởi các Nhà Bán Hàng ở ngoài lãnh thổ Việt Nam (Nhà bán hàng hoặc một Sàn TMĐT khác):</p>
           <ul style="box-sizing: border-box; list-style: outside disc; margin: 20px 0px 20px 20px; padding: 0px 0px 0px 20px; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
               <li style="box-sizing: border-box;">Hàng quốc tế được hiểu là hàng hoá bán/cung cấp qua biên giới mà khách hàng mua trực tiếp từ nước ngoài.</li>
               <li style="box-sizing: border-box;">Hàng quốc tế được hiểu là hàng hoá mua về phục vụ nhu cầu cá nhân, <a href="http://nmkshop.somee.com" style="box-sizing: border-box; background-color: transparent; color: rgb(0, 65, 137); text-decoration: none;">NMKSHOP.SOMEE.COM</a> là đơn vị trung gian giữa Nhà Bán Hàng và Khách Hàng.</li>
               <li style="box-sizing: border-box;">Khách Hàng có thể nhận diện sản phẩm mua trực tiếp từ nước ngoài bằng dòng chữ bên dưới &quot;Hàng quốc tế&quot;.</li>
           </ul>
           <p style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
               <strong style="box-sizing: border-box; font-weight: bold;">2. Đối tượng áp dụng:</strong></p>
           <ul style="box-sizing: border-box; list-style: outside disc; margin: 20px 0px 20px 20px; padding: 0px 0px 0px 20px; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
               <li style="box-sizing: border-box;">
                   <p style="box-sizing: border-box;">
                       Khách Hàng mua hàng hóa từ Nhà Bán Hàng ngoài lãnh thổ Việt Nam trên trang thương mại điện tử:<span>&nbsp;</span><a href="http://www.nmkshop.somee.com" style="box-sizing: border-box; background-color: transparent; color: rgb(0, 65, 137); text-decoration: none;">www.nmkshop.somee.com</a>.</p>
               </li>
           </ul>
           <p style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
               <strong style="box-sizing: border-box; font-weight: bold;">3.</strong>&nbsp;<strong style="box-sizing: border-box; font-weight: bold;">Chính sách đặt hàng và giao hàng:</strong></p>
           <p style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
               <strong style="box-sizing: border-box; font-weight: bold;">a.&nbsp;Chính sách đặt hàng:</strong></p>
           <ul style="box-sizing: border-box; list-style: outside disc; margin: 20px 0px 20px 20px; padding: 0px 0px 0px 20px; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
               <li style="box-sizing: border-box;">Khách hàng sau khi đặt hàng và thanh toán thành công đối với các sản phẩm có biểu tượng &quot;hàng giao từ nước ngoài&quot; <a href="http://nmkshop.somee.com"style="box-sizing: border-box; background-color: transparent; color: rgb(0, 65, 137); text-decoration: none;">NMKSHOP.SOMEE.COM</a> rất tiếc sẽ chưa thể hỗ trợ hủy đơn hàng.</li>
               <li style="box-sizing: border-box;"><span style="box-sizing: border-box;">Giá bán sản phẩm đã bao gồm các phí, thuế phát sinh trong quá trình vận chuyển thông quan về Việt Nam và chưa bao gồm phí vận chuyển chặng cuối giao hàng trong lãnh thổ Việt Nam. Phí vận chuyển giao hàng trong lãnh thổ Việt Nam sẽ áp dụng theo chính sách giao hàng chung của <a href="http://nmkshop.somee.com" style="box-sizing: border-box; background-color: transparent; color: rgb(0, 65, 137); text-decoration: none;">NMKSHOP.SOMEE.COM</a> đối với khách hàng đặt hàng.</span></li>
               <li style="box-sizing: border-box;">Hình thức thanh toán:</li>
           </ul>
           <p style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; + Thanh toán bằng tiền mặt khi nhận hàng (tuỳ thuộc một số loại sản phẩm có thể hỗ trợ hình thức thanh toán này).</p>
           <p style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; + Thanh toán bằng thẻ quốc tế Visa, Master, JCB.</p>
           <p style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; + Thanh toán bằng thẻ ATM nội địa/Internet Banking;</p>
           <p style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; + Thanh toán bằng Ví điện tử Momo.</p>
           <ul style="box-sizing: border-box; list-style: outside disc; margin: 20px 0px 20px 20px; padding: 0px 0px 0px 20px; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
               <li style="box-sizing: border-box;"><span style="box-sizing: border-box;">Khách hàng đặt đơn hàng không đặt quá 10kg trên mỗi đơn hàng do việc thông quan có thể không thành công.</span></li>
               <li style="box-sizing: border-box;">Tiki rất tiếc chưa hỗ trợ xuất hóa đơn với các sản phẩm giao từ nước ngoài.</li>
           </ul>
           <p style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
               <strong style="box-sizing: border-box; font-weight: bold;">b.&nbsp;Chính sách giao hàng:</strong></p>
           <ul style="box-sizing: border-box; list-style: outside disc; margin: 20px 0px 20px 20px; padding: 0px 0px 0px 20px; color: rgb(51, 51, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
               <li style="box-sizing: border-box;"><span style="box-sizing: border-box;">Thời gian giao hàng:<span>&nbsp;</span>Từ 8 (tám) đến 15 (mười lăm)<span>&nbsp;</span>ngày tùy theo quốc gia giao hàng, điều kiện địa lý, vận chuyển và được ước tính trong thông tin đơn hàng cho Khách hàng.</span></li>
               <li style="box-sizing: border-box;"><span style="box-sizing: border-box;">Cam kết giao hàng: <a href="http://nmkshop.somee.com" style="box-sizing: border-box; background-color: transparent; color: rgb(0, 65, 137); text-decoration: none;">NMKSHOP.SOMEE.COM</a> chỉ cam kết ước tính thời gian giao hàng, thời gian giao hàng thực tế có thể chênh lệch tùy thuộc vào hàng hóa, điều kiện nhập khẩu, các yếu tố địa lý, thời tiết tại các quốc gia khác nhau.</span></li>
               <li style="box-sizing: border-box;">Trong trường hợp quá 15 (mười lăm) ngày kể từ thời gian giao hàng dự kiến, nếu Tiki chưa thể thực hiện giao hàng cho Khách Hàng thì Tiki sẽ hoàn tiền 100% giá trị đơn hàng cho Khách Hàng, trừ các trường hợp thuộc sự kiện bất khả kháng bao gồm nhưng không giới hạn thiên tai, lũ lụt, tranh chấp thương mại, lãnh công, thiếu thốn về nguyên vật liệu, …</li>
               <li style="box-sizing: border-box;"><span style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: bold;">Đối với trường hợp đơn hàng giao hàng không thành công, <a href="http://thietbidientu.somee.com" style="box-sizing: border-box; background-color: transparent; color: rgb(0, 65, 137); text-decoration: none;">NMKSHOP.SOMEE.COM</a> hỗ trợ giao hàng tối đa 03 (ba) lần. Sau đó hàng sẽ được giữ tại Kho Tiki trong vòng 14 (mười bốn) ngày, trong thời gian này, <a href="http://nmkshop.somee.com" style="box-sizing: border-box; background-color: transparent; color: rgb(0, 65, 137); text-decoration: none;">NMKSHOP.SOMEE.COM</a>sẽ cố gắng giao lại đơn hàng tuy nhiên không cam kết về vấn đề này. Tùy theo tình hình vận chuyển, đơn hàng vẫn có thể sẽ không được giao lại theo yêu cầu của quý khách.<span>&nbsp;</span><span class="wysiwyg-color-red" style="box-sizing: border-box; color: rgb(255, 0, 0);">Quá thời hạn trên, NMKSHOP sẽ từ chối giao hàng lại và đơn hàng được coi như thành công, Tiki không chịu trách nhiệm về tình trạng của hàng hóa và không có trách nhiệm hoàn tiền cho Khách Hàng.</span></strong></span></li>
           </ul>
           <h2>&nbsp;</h2>
     </div>

        </body>
    </html>
</asp:Content>
